sudo: required

dist: trusty

language: rust

os:
  - linux

rust:
  - nightly
  - beta
  - stable

addons:
  apt:
    packages:
      - gcc

before_script:
  - git submodule update --init --recursive

script:
  - (cd croaring-sys && cargo test)
  - cargo test
  - |
    [ $TRAVIS_RUST_VERSION != nightly ] ||
    cargo bench
